import axios from 'axios';
import cloudinary from '../config/cloudinary';
import prisma from '../config/database';

export class AIService {
  async generateVisual(
    productImage: string,
    style: string,
    prompt: string,
    userId: string,
    projectId: string,
  ) {
    try {
      // 1. Build a detailed prompt that includes the style
      const fullPrompt = `Create a premium e-commerce product visual. Style: ${style}. ${prompt}`;
      
      // 2. Call the Gemini API (using the free gemini-2.0-flash-exp model)
      // Note: This model can generate images directly from text prompts.
      const response = await axios.post(
        `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent?key=${process.env.GEMINI_API_KEY}`,
        {
          contents: [{
            parts: [{ text: fullPrompt }]
          }],
          generationConfig: {
            responseModalities: ["TEXT", "IMAGE"]
          }
        },
        {
          headers: { 'Content-Type': 'application/json' }
        }
      );

      // 3. Extract the image data (base64) from the response
      const parts = response.data.candidates[0].content.parts;
      const imagePart = parts.find((part: any) => part.inlineData);
      
      if (!imagePart) {
        throw new Error('No image generated by Gemini');
      }

      // 4. Convert base64 to a buffer for Cloudinary upload
      const imageBuffer = Buffer.from(imagePart.inlineData.data, 'base64');

      // 5. Upload the generated image to Cloudinary
      const result = await new Promise((resolve, reject) => {
        cloudinary.uploader.upload_stream(
          {
            folder: `visualforge/users/${userId}/projects/${projectId}/generated`,
            public_id: `generated_${Date.now()}`,
          },
          (error, result) => error ? reject(error) : resolve(result)
        ).end(imageBuffer);
      });

      // 6. Save the result as an ImageAsset in your database
      const imageAsset = await prisma.image.create({
        data: {
          userId,
          projectId,
          type: 'GENERATED',
          originalName: `gemini_generated_${Date.now()}`,
          secureUrl: (result as any).secure_url,
          publicId: (result as any).public_id,
          format: (result as any).format || 'png',
          width: (result as any).width,
          height: (result as any).height,
          bytes: (result as any).bytes,
        },
      });

      // 7. Log the activity for the user's history
      await prisma.activity.create({
        data: {
          userId,
          projectId,
          action: 'GENERATE',
          description: `Generated visual with style: ${style} using AI`,
        },
      });

      return imageAsset;

    } catch (error: any) {
      console.error('AI Generation Error:', error.response?.data || error.message);
      throw new Error('AI generation failed. Please check your API key and prompt.');
    }
  }
}

export const aiService = new AIService();